#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  4 19:51:45 2017

@author: wheelspawn
"""

print("A=", ((2**3)/5)-(7*3))
print("A=", (2**(3/5))-(7*3))
print("A=", (2**((3/5)-(7*3))))
print("A=", (2**(3/(5-(7*3)))))